commerce/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='product')),
    path('account/', include('account.urls')),
    path('cart', include('cart.urls', namespace='cart')),
    path('kupon/', include('kupon.urls', namespace='kupon')),
    path('', include('payment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/kupon/urls.py
from django.urls import path
from . import views

app_name = 'kupon'

urlpatterns = [
    path('disc/', views.kupon_disk, name='disc')
]

commerce/product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

commerce/cart/models.py
from django.db import models

# Create your models here.

commerce/cart/forms.py
from django import forms

JLH_PRODUCT = [(i, str(i)) for i in range(1, 10)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=JLH_PRODUCT, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

commerce/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from product.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from kupon.forms import KuponApplyForm
from django.views.decorators.http import require_POST

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                 override_quantity=cd['override'])
        return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity':item['quantity'],
                                                                   'override':True})
    count = 0
    for item in cart:
        count += item['quantity']

    kupon_form = KuponApplyForm()

    context = {
        'cart':cart,
        'count':count,
        'kupon_form': kupon_form,
    }

    return render(request, 'cart/cart_detail.html', context)

commerce/templates/cart/cart_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Keranjang Belanja
{% endblock %}

{% block content %}
    <h1>Keranjang Belanja Anda</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Harga Unit</th>
                <th>Harga</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img class="img-fluid" style="width:250px" src="{% if product.image %}{{ product.image.url}} {% else %}{% static 'img/no_image.png' %}{% endif %}">
                    </a>
                </td>
                <td>
                    {{ product.name }}

                </td>
                <td>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.override }}
                        <input class="btn btn-primary" type="submit" value="Update">
                        {% csrf_token %}
                    </form>
                </td>

                <td>
                    <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                        <input class="btn btn-primary" type="submit" value="Remove">
                        {% csrf_token %}
                    </form>
                </td>
                <td class="num">
                    Rp {{ item.price }}
                </td>
                <td class="num">
                    Rp {{ item.total_price }}
                </td>
            </tr>
            {% endwith %}
            {% endfor %}

            {% if cart.kupon %}
            <tr class="subtotal">
                <td>Subtotal</td>
                <td colspan="4"></td>
                <td class="num">Rp {{ cart.get_total_price }}</td>
            </tr>
            <tr>
                <td>
                    "{{ cart.kupon.code }}" kupon
                    ({{ cart.kupon.diskon }}%)
                </td>
                <td colspan="4"></td>
                <td class="num neg">
                    - Rp {{ cart.get_disc }}
                </td>
            </tr>
            {% endif %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">
                    Rp {{ cart.get_total_price_after_discount }}
                </td>
            </tr>

        </tbody>
    </table>

    <p>Masukkan Kupon Diskon :</p>
    <form action="{% url 'kupon:disc' %}" method="post">
        {{ kupon_form }}
        <input class="btn btn-primary" type="submit" value="Apply">
        {% csrf_token %}
    </form>

    <p class="text-right">
        <a href="{% url 'product:product_list' %}"><button type="submit" class="btn btn-primary">Lanjut Belanja</button></a>
        <a href="{% url 'checkout' %}"><button type="submit" class="btn btn-primary">Checkout</button></a>
    </p>
    {% endblock %}